---
title: "monarchs and marriages"
author: "fth"
format: gfm
---

# notes:
get the list of English monarchs and their marriage ages. 

# data location: 
https://www.ianvisits.co.uk/articles/a-list-of-monarchs-by-marriage-6857/

```{r, setup}
library(dplyr)
library(stringr)
library(rvest)
library(ggplot2)

```

# get dataset

```{r}

# url to scrape:
root <- "https://www.ianvisits.co.uk/articles/a-list-of-monarchs-by-marriage-6857/"
 
# get table
tables <- read_html(root) %>% html_nodes("table")
df <- tables[1] %>% html_table() %>% as.data.frame()

df <- df[, -6]      # remove spoiler 
df <- df[-c(1,2), ] # remove double-header effect

cols <- c("king_name", "king_age", "consort_name", "consort_age", "year_of_marriage")
colnames(df) <- cols

```

# quick eda 

```{r}

df %>% 
  mutate(
    king_age = as.numeric(king_age),
    consort_age = as.numeric(consort_age),
    year_of_marriage = as.numeric(year_of_marriage)
  ) %>% 
  ggplot(.) + 
  geom_point(aes(x = year_of_marriage, y = consort_age, color = "Consort Age"), size = 3) + 
  geom_point(aes(x = year_of_marriage, y = king_age, color = "King Age"), size = 3) + 
   geom_smooth(aes(x = year_of_marriage, y = consort_age, color = "Consort Age"), span = .4) + 
   geom_smooth(aes(x = year_of_marriage, y = king_age, color = "King Age"), span = .4) + 
  ggdark::dark_mode() + 
  labs(
    title = "English Monarchs and Age of Marriage"
      ) + 
  PrettyCols::scale_color_pretty_d("Rainbow")

```

